### ISSUE TITLE
testBug

### ISSUE THREAD

**Issue by pandorawanz** [hcsp/print-prime-numbers-in-100#18]
test貌似有bug，见如下两个提交，都能通过测试
[https://github.com/hcsp/print-prime-numbers-in-100/pull/16](https://github.com/hcsp/print-prime-numbers-in-100/pull/16)
[https://github.com/hcsp/print-prime-numbers-in-100/pull/17](https://github.com/hcsp/print-prime-numbers-in-100/pull/17)
不同点在于j<Math.sqrt(i)+1处是否有+1

**Comment by blindpirate** [comment]
你要是喜欢的话，把`for (int j = 2; j <Math.sqrt(i); j++)`换成`for (int j = 2; j <i; j++)`也是可以通过的啊。。。判断一个数是不是质数，判断到`Math.sqrt()`即可， 再往多了判断只是多余而已，并不影响结果的正确性。
